### ISSUE TITLE
Cannot mount GOG game.ins files 

### ISSUE THREAD

**Issue by dhollinger** [schellingb/dosbox-pure#18]
I'm on an Ubuntu 20.10-based operating system and I cannot mount GOG `game.ins` files within dosbox-pure.

A `game.ins` file is equivalent to a `.cue` file, but makes some assumptions that can cause problems for non-windows dosbox users under certain circumstances (such as not using GOG's provided version of Dosbox).

I believe this is related to an issue that existed in both `dosbox-staging` and `boxtron`

Link to dosbox-staging issue: https://github.com/dosbox-staging/dosbox-staging/issues/349

EDIT: DosBox Staging fix can be found in this PR: https://github.com/dosbox-staging/dosbox-staging/pull/674

**Comment by dhollinger** [comment]
Looks like the remainder of the work was/is done in this issue: https://github.com/dosbox-staging/dosbox-staging/issues/102

**Comment by schellingb** [comment]
Interesting. Why would they have wrong file capitalization in the cue files, that sounds ridiculous but ok.

So the .ins files are just differently named .cue files? I'll add .ins to the list of supported extensions for this core and make the cue sub-file loading case insensitive then. Stay tuned, thanks for reporting!

**Comment by schellingb** [comment]
Hopefully fixed in 0.3. Please try it out!

**Comment by dhollinger** [comment]
It seems to work for me in 0.3

I still have some issues with the game running too fast, but that can wait until dosbox config files are supported
