### ISSUE TITLE
Sound bugs in version 0.21

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#222]
I just updated from 0.20 to 0.21 and i'm now getting random blips and bloops in the midi music every now and then.

Seems to clear up if i force 60fps in the core options but that's something i didn't need to do in 0.20. Plus, if i force 60fps, games run a bit jerkier.

I have a 240hz gsync monitor.

**Comment by 71knight** [comment]
Yes I noticed the same thing with a 60 hertz phone.  Midi has had this problem for the longest, except for me it sounded like static every minute or so.

**Comment by schellingb** [comment]
A few questions to help me pin this down:
- Is this only affecting MIDI and no other audio output like Adlib music, CD music or regular sound blaster output?
- What are the MIDI output settings (SF2 or MT32 or frontend MIDI)?
- Was any other core option modified or is everything on default?
- Is this during gameplay or does it also happen while nothing else is active (for example the music test in SETUP.EXE of Duke3D)?

I "only" have a 144hz screen but I can't reproduce this fully. I do have some glitches when a game loads a lot of data or when I switch between the RetroArch menu and the game, but for me this was much worse in older versions.

**Comment by Tasosgemah** [comment]
I use the sound font option since frontend midi was always buggy for me and i don't like the sound of the older Soundblaster cards. So i'm using a font that sounds very close to general midi. Don't know if these sound bugs occur with other options. I will be away from my PC for a week so i can't test more for the time being.

The bugs happen during gameplay. Every 30-40 seconds or so, i'm getting a sound bug. It's either a blip/bloop sound or a cut off. Feels like an audio sync issue to me.

I do use the new timing mode in 0.20 and i don't get these sound bugs. I tested both DOOM and Duke Nukem 3D and both behave the same (sound issues every 30-40 seconds in 0.21, no issues in 0.20).

I don't think i changed much of the other core options.

I have a 240hz monitor and the freesync option in the general RetroArch options is always enabled.

**Comment by 71knight** [comment]
For me it only affects Midi using mt-32 setting.  The only option I have enabled is force 60fps output with input latency at default.  It happens mainly during gameplay.

**Comment by 71knight** [comment]
Just did some more testing on my Android phone.  When I turn Force 60fps output off, the static/blip in the midi goes away.  Apparently changing the force 60fps output messes up the timing in relation to the estimated refresh rate of the screen.  It may somehow affect the sound buffer causing the issue.

**Comment by Tasosgemah** [comment]
For me its the opposite. 60fps fixes the sound issues but im using a 240hz feesync monitor.

**Comment by Tasosgemah** [comment]
Thank you, i will be testing this after i get back to my PC

**Comment by 71knight** [comment]
In the time that I played ver 0.22 that should have had audio hickups and midi blips, now everything seems to have been fixed!  I think the source of the problem may have been the addition of low input latency and force 60fps output settings messing up retroarch's estimated screen refresh setting causing slight audio buffer underruns.  Just my thought!

**Comment by gordon81-afk** [comment]
Hello, afer update to 0.22, something was wrong in windows version of the core.

Now the "Force 60 fps output" enabled option breaks the music or sound, 

This is the example video i have recorded:

https://files.fm/u/sdkr66vq9

When the video starts, you can hear how the music and the sounds has aleatory snaps.

I have used a fresh reatroarch installation.

Please, could you fix it? the 0.21 version works fine with "force 60 fps output" enabled.

Thank you very much and happy new year.

**Comment by schellingb** [comment]
@gordon81-afk Thank you for reporting this, you're absolutely right. Looks like we'll get 0.23 sooner than expected :-)

**Comment by schellingb** [comment]
Audio issues with "Force 60FPS Output" should now be fixed in the just released 0.23.

**Comment by gordon81-afk** [comment]
Sorry bad news, @schellingb  the music bug still with 0.23.

https://files.fm/u/2tb6w8ae9

My system specs:

[url=https://ibb.co/9bghNnq][img]https://i.ibb.co/zXxFrsS/1.jpg[/img][/url]
[url=https://imgbb.com/][img]https://i.ibb.co/BKr8TBx/2.jpg[/img][/url]
[url=https://ibb.co/mHktKyC][img]https://i.ibb.co/4jzMLSZ/3.jpg[/img][/url]

My monitor is not a freesync, it has 60hz.

However the 0.20 version still works fine.

I have tested the 0.23 in different systems, and they have same problems with the sound when "force 60fps output" is enabled.

Super Star Wars game or Blackthorne show this bug more clear.

I hope you can fix it, thank you very much.

**Comment by schellingb** [comment]
Aha! Thanks for verifying this again. Turns out Super Star Wars runs at 320x200 at a refresh rate of 54.82 Hz. "Force 60 FPS" was actually broken for that case, running that game at 109% speed and the sound stuttering was just the 9% that had no audio.

Btw. you can check that yourself by setting `Show Performance Statistics` to `Detailed` in the core's emulation options. It will show the emulated display mode and a speed percentage (which should always be near 100% otherwise something is bad).

Regarding Lands of Lore 2, I'll see if I can test that tomorrow.

**Comment by gordon81-afk** [comment]
I can confirm these config for lands of lore 2 guardians of destiny runs flawlesly in 0.20-0.21-0.22

dosbox_pure_advanced = "true"
dosbox_pure_aspect_correction = "true"
dosbox_pure_audiorate = "48000"
dosbox_pure_auto_mapping = "true"
dosbox_pure_auto_target = "0.9"
dosbox_pure_bind_unused = "true"
dosbox_pure_cga = "early_auto"
dosbox_pure_cpu_core = "auto"
dosbox_pure_cpu_type = "auto"
dosbox_pure_cycles = "500000"
dosbox_pure_cycles_scale = "1.0"
dosbox_pure_experimental_timing_mode = "new"
dosbox_pure_force60fps = "true"
dosbox_pure_gus = "false"
dosbox_pure_hercules = "white"
dosbox_pure_joystick_analog_deadzone = "15"
dosbox_pure_joystick_timed = "true"
dosbox_pure_keyboard_layout = "sp"
dosbox_pure_latency = "default"
dosbox_pure_machine = "svga"
dosbox_pure_memory_size = "16"
dosbox_pure_menu_time = "5"
dosbox_pure_midi = "scummvm/extra/8bitsf.SF2"
dosbox_pure_mouse_input = "true"
dosbox_pure_mouse_speed_factor = "1.6"
dosbox_pure_mouse_speed_factor_x = "1.0"
dosbox_pure_mouse_wheel = "67/68"
dosbox_pure_on_screen_keyboard = "true"
dosbox_pure_perfstats = "detailed"
dosbox_pure_savestate = "on"
dosbox_pure_sblaster_adlib_emu = "nuked"
dosbox_pure_sblaster_adlib_mode = "opl3gold"
dosbox_pure_sblaster_conf = "A220 I7 D1 H5"
dosbox_pure_sblaster_type = "sbpro1"
dosbox_pure_svga = "vesa_oldvbe"

I repeat, with your dosbox pure, lands of lore guardians of destiny runs better than windows 95 version.

You can make lands of lore 2 run again in 0.23?

Thank you!!!

**Comment by schellingb** [comment]
And this happens right when starting the game, before the Westwood logo or anything? Which (of the many) EXE files are you using to start? Is it `LOLG.EXE` or `RUNGAME.EXE`? Either of those run fine for me with these options and the 0.23 I released yesterday on Windows 64bit.

**Comment by gordon81-afk** [comment]
I´m so sorry

I have reset settings in lands of lore 2 and now it run flawlesly.

With these setting the game runs at 60-70fps very well.

dosbox_pure_aspect_correction = "true"
dosbox_pure_audiorate = "48000"
dosbox_pure_auto_mapping = "true"
dosbox_pure_auto_target = "0.9"
dosbox_pure_bind_unused = "true"
dosbox_pure_cga = "early_auto"
dosbox_pure_cpu_core = "auto"
dosbox_pure_cpu_type = "auto"
dosbox_pure_cycles = "500000"
dosbox_pure_cycles_scale = "1.0"
dosbox_pure_force60fps = "true"
dosbox_pure_gus = "false"
dosbox_pure_hercules = "white"
dosbox_pure_joystick_analog_deadzone = "15"
dosbox_pure_joystick_timed = "true"
dosbox_pure_keyboard_layout = "us"
dosbox_pure_latency = "default"
dosbox_pure_machine = "svga"
dosbox_pure_memory_size = "16"
dosbox_pure_menu_time = "5"
dosbox_pure_midi = "scummvm/extra/8bitsf.SF2"
dosbox_pure_mouse_input = "true"
dosbox_pure_mouse_speed_factor = "1.0"
dosbox_pure_mouse_speed_factor_x = "1.0"
dosbox_pure_mouse_wheel = "67/68"
dosbox_pure_on_screen_keyboard = "true"
dosbox_pure_perfstats = "none"
dosbox_pure_savestate = "on"
dosbox_pure_sblaster_adlib_emu = "default"
dosbox_pure_sblaster_adlib_mode = "auto"
dosbox_pure_sblaster_conf = "A220 I7 D1 H5"
dosbox_pure_sblaster_type = "sb16"
dosbox_pure_svga = "svga_s3"


thank you very much and so sorry by my mistake.

**Comment by schellingb** [comment]
@gordon81-afk The fix is now in the just released 0.24, if you could test Super Star Wars or Blackthorne again I'd be grateful.

**Comment by gordon81-afk** [comment]
Thank you very much @schellingb.

Right now your core runs perfect with both games.

I think you have found the perfect timming.

I love you!!.

**Comment by Tasosgemah** [comment]
Sound bugs have been fixed for me too.

**Comment by schellingb** [comment]
Awesome, great to hear. I'll close this issue then. If there are new issues regarding audio output, please open a new issue.
