### ISSUE TITLE
0.9.8 creates unnecessary subfolder for save states.

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#442]
I use the option for each core to save inside their own core-named folder.

With 0.9.7, the save states were stored in "states/DOSbox-pure"

With 0.9.8, the save states are stored in "states/DOSbox-pure/DOSbox-pure"

Is this an intentional change? Not sure how it helps.

**Comment by schellingb** [comment]
Looks like this is an issue with RetroArch when using a new libretro interface we use for enabling Netplay for DOS games. So until this is fixed in RetroArch we are kinda stuck...  We maybe need to disable Netplay support until the fix is common in a stable release of RetroArch :-(

**Comment by schellingb** [comment]
Please try the newly released 0.9.9.
It should be fixed with any stable RetroArch version (up to latest 1.16) and recent nightly builds of RetroArch. If you use an older nightly build of RetroArch (between 2 and 6 weeks old) it might still be broken.

**Comment by Tasosgemah** [comment]
Yeah, it works on the latest nightly. On the previous one i used it's still broken like you said (it's from 15 Nov).

**Comment by Massouille78** [comment]
Hello, It is ok now for me on the last version 0.9.9,

Thanks very much

**Comment by PoloniumRain** [comment]
I can also confirm that this issue is now fixed in both RA 1.16 and the latest nightly.
